
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import CallIcon from "./_components/CallIcon";

export const myFont = localFont({
  src: "../public/font/Dana-Bold.woff2",
});

export const metadata = {
  title: "نئون ویچ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} antialiased bg-[#f4f4f4]`}
      >
        <Navbar />
        {children}
        <CallIcon />
        <Footer />
      </body>
    </html>
  );
}
